# Generated by Django 2.1.3 on 2018-11-28 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereviews',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbim.Movie', unique=True),
        ),
        migrations.AlterField(
            model_name='moviereviews',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbim.Review', unique=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbim.Movie', unique=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbim.Person', unique=True),
        ),
    ]
