# Generated by Django 2.1.3 on 2018-11-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbim', '0003_auto_20181128_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='Best movie ever'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.IntegerField(),
        ),
    ]
